---
#- hosts: localhost
#  tasks:
  - name: Check whether Java is installed or not
    command: java -version
    register: java_result
  - debug: 
      msg: "Failed - Java is not installed"
    when: java_result is failed
  - debug:
      msg: "Success - Java is installed"
    when: java_result is success
  - name: install play_role_2 if java isn't installed
    command: ansible-galaxy install --roles-path . -r /home/U65986/requirements1.yml
#  - unarchive:
#      src: https://github.com/KarthikSadashiva/DigitalAlpha/raw/master/SSDevops-Learning.zip
#      dest: /home/U65986/Requirement/playbook/roles/
#      remote_src: True
#    become: yes
#    when: "Failed - Java is not installed"
